### ISSUE TITLE
TypeError: createOperationSelector is not a function

### ISSUE THREAD

**Issue by l3roken** [relay-tools/found-relay#168]
I am getting the following error and I can't seem to passed it:

```

Resolver.js:207 Uncaught (in promise) TypeError: createOperationSelector is not a function
    at http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:19212:65
    at Array.map (<anonymous>)
    at Resolver.updateQuerySubscriptions (http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:19198:38)
    at Resolver._callee$ (http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:19094:41)
    at tryCatch (http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:2296:40)
    at Generator.invoke [as _invoke] (http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:2530:22)
    at Generator.prototype.(anonymous function) [as next] (http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:2348:21)
    at resume (http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:1820:30)
    at http://home.devbox:42450/vendors~main.1d7887f6607d23311910.js:1813:11
    at new Promise (<anonymous>)

```

**Comment by taion** [comment]
this is https://github.com/relay-tools/found-relay/issues/159

**Comment by l3roken** [comment]
I downgraded to 1.70 and its working.  Thanks

**Comment by taion** [comment]
actually, if you use the alphas for the next release, we have relay v2 support now

**Comment by episodeyang** [comment]
This issue is god-send!!

I'm running into the same issue. Upgrading to `found-replay@next` solved the issue (`@next` points to `0.4.0-alpha.4`).

**Comment by smooth-opperator** [comment]
I've upgraded to v0.4.0-alpha.6, but now I'm just back to a previous error
`TypeError: Cannot read property 'store' of undefined`
seems to be coming from:
```
at renderElement (/node_modules/found-relay/lib/renderElement.js:44:16)
at /node_modules/found-relay/lib/Resolver.js:217:48
```

**Comment by taion** [comment]
See discussion in https://github.com/4Catalyzer/found/issues/244. You need to make sure you're using a version of `found` that is compatible with your version of `react-redux`; either the v0.4.x alphas for React Redux v6.x, or the v0.3.x releases for React Redux v5.x.

**Comment by smooth-opperator** [comment]
that's the issue that brought me here ;-)
am using 
"found": "v0.4.0-alpha.1",
"react-redux": "^6.0.1",

**Comment by taion** [comment]
You need to be on at least alpha 7 to get a compat bugfix per https://github.com/4Catalyzer/found/releases/tag/v0.4.0-alpha.7.
